services:
  gitea:
    image: docker.gitea.com/gitea:1.26.4
    container_name: gitea
    restart: always
    environment:
      USER_UID: 1000
      USER_GID: 1000
    volumes:
      - ./storage/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3002:3000"
      - "2222:22"

  registry:
    image: registry:3.1.1
    container_name: registry
    restart: always
    volumes:
      - ./storage/registry:/var/lib/registry
    ports:
      - "3003:5000"

  athens:
    image: gomods/athens:v0.18.0
    container_name: athens-proxy
    restart: always
    environment:
      ATHENS_DISK_STORAGE_ROOT: /var/lib/athens
      ATHENS_STORAGE_TYPE: disk
    volumes:
      - ./storage/athens:/var/lib/athens
    ports:
      - "3001:3000"
